import type { Scenario } from "./types";

// Shared baseline for users who are eligible unless a scenario deliberately
// mutates age verification or watchlist status.
const verified = {
  country_code: "US",
  is_age_verified: true,
  is_on_watchlist: false,
};

// This array is data-driven demo coverage. Each scenario supplies both the
// Temporal start payload defaults and the UI copy needed to explain what a
// requester, approver, and recipient would see during that workflow path.
export const scenarios: Scenario[] = [
  {
    id: "double-opt-in",
    title: "Same Age Group Double Opt-In",
    navLabel: "Double opt-in",
    group: "Friends API",
    objective: "Two friends in an allowed same-age band request and accept trusted friend status.",
    entryPoint: "Friends API: SendTrustedFriend and AcceptTrustedFriend",
    sourceChannel: "STANDARD",
    requester: { id: "dana18", label: "Dana", snapshot: { ...verified, age: 18 } },
    target: { id: "morgan19", label: "Morgan", snapshot: { ...verified, age: 19 } },
    areFriends: true,
    parentChildRelationship: false,
    autoAccept: false,
    consentTtlSeconds: 120,
    trigger: "DOUBLE_OPT_IN",
    expectedInitialStatus: "PENDING",
    requirements: ["Friends already", "Both 18+ or both 16-17", "Double opt-in acceptance"],
    previews: {
      requester: {
        title: "Dana's request",
        idle: "Dana can send Morgan a trusted friend request from the friends screen.",
        pending: "Dana sees the request as sent and waiting for Morgan to accept.",
        waiting: "Dana sees the request held while required approval is completed.",
        trusted: "Dana sees Morgan promoted to trusted friend status.",
        blocked: "Dana sees that this trusted friend request cannot complete right now.",
        detail: "Standard friends API flow for an eligible same-age friend pair.",
      },
      approver: {
        title: "Approval view",
        idle: "No approval task exists until a request is sent.",
        pending: "No parent review is queued for this adult same-age request.",
        waiting: "No parent review is queued for this adult same-age request.",
        trusted: "No parent review was needed before the connection became trusted.",
        blocked: "No parent review can override an ineligible or denied pair.",
        notRequired: "No parent approval required: both users are 18+ and already friends.",
        detail: "The demo keeps this pane visible so presenters can confirm why approval is skipped.",
      },
      recipient: {
        title: "Morgan's inbox",
        idle: "Morgan has not received a trusted friend prompt yet.",
        pending: "Morgan sees Dana's request and can accept it.",
        waiting: "Morgan sees the request waiting on required approval before it can finish.",
        trusted: "Morgan sees Dana listed as a trusted friend.",
        blocked: "Morgan sees that the request is no longer available.",
        detail: "The recipient acceptance signal completes the double opt-in.",
      },
    },
    actions: [
      { kind: "start", label: "Send request", description: "Start the pair workflow in PENDING." },
      { kind: "accept", label: "Accept", description: "Signal AcceptTrustedFriend." },
    ],
  },
  {
    id: "irl-auto-upgrade",
    title: "IRL Friending Auto-Upgrade",
    navLabel: "IRL auto-upgrade",
    group: "Auto upgrade",
    objective: "A 13+ friendship formed through an IRL channel becomes trusted immediately.",
    entryPoint: "CreateFriendship / QR code / Contact List Importer event",
    sourceChannel: "CONTACT_LIST_IMPORTER",
    requester: { id: "ivy14", label: "Ivy", snapshot: { ...verified, age: 14 } },
    target: { id: "leo15", label: "Leo", snapshot: { ...verified, age: 15 } },
    areFriends: true,
    parentChildRelationship: false,
    autoAccept: true,
    consentTtlSeconds: 120,
    trigger: "IRL_AUTO_UPGRADE_CONTACT_LIST_IMPORTER",
    expectedInitialStatus: "TRUSTED",
    requirements: ["Both users are 13+", "Friendship formed through QR or Contact List Importer", "No extra accept click"],
    previews: {
      requester: {
        title: "Ivy's contact import",
        idle: "Ivy can create an IRL friendship from a contact importer match.",
        pending: "Ivy sees the IRL friendship being upgraded.",
        waiting: "Ivy sees the upgrade paused while approval is checked.",
        trusted: "Ivy sees Leo added as a trusted friend immediately.",
        blocked: "Ivy sees that the IRL upgrade is unavailable.",
        detail: "IRL source channels can auto-upgrade eligible 13+ friends.",
      },
      approver: {
        title: "Approval view",
        idle: "No approval task exists before the IRL friendship is created.",
        pending: "No parent review is queued for this IRL auto-upgrade.",
        waiting: "No parent review is queued for this IRL auto-upgrade.",
        trusted: "No approval was required for this eligible 13+ IRL friendship.",
        blocked: "No approval can override a failed eligibility check.",
        notRequired: "No parent approval required: both users are 13+ and the friendship came from an IRL channel.",
        detail: "The approver pane explains why the flow completes without an extra review step.",
      },
      recipient: {
        title: "Leo's friend screen",
        idle: "Leo has not created the IRL friendship yet.",
        pending: "Leo sees the trusted status being applied from the IRL friend event.",
        waiting: "Leo sees the connection waiting for approval to finish.",
        trusted: "Leo sees Ivy as a trusted friend without another accept click.",
        blocked: "Leo sees that the trusted upgrade did not complete.",
        detail: "The contact importer event acts as the trusted friend opt-in.",
      },
    },
    actions: [
      { kind: "start", label: "Create IRL friendship", description: "Auto-start and auto-accept trusted connection." },
    ],
  },
  {
    id: "parent-child-auto",
    title: "Parent-Child Auto-Upgrade",
    navLabel: "Parent-child",
    group: "Auto upgrade",
    objective: "A friend pair with a parent-child relationship becomes trusted once eligibility is met.",
    entryPoint: "Parent-child relationship formed / eligibility processor",
    sourceChannel: "PARENT_CHILD",
    requester: { id: "parent42", label: "Parent", snapshot: { ...verified, age: 42 } },
    target: { id: "teen14", label: "Teen", snapshot: { ...verified, age: 14 } },
    areFriends: true,
    parentChildRelationship: true,
    autoAccept: true,
    consentTtlSeconds: 120,
    trigger: "PARENT_CHILD_AUTO_UPGRADE",
    expectedInitialStatus: "TRUSTED",
    requirements: ["Friends already", "Recognized parent-child relationship", "Age verified"],
    previews: {
      requester: {
        title: "Parent's trusted list",
        idle: "Parent can form a recognized parent-child relationship with Teen.",
        pending: "Parent sees the relationship being checked for trusted access.",
        waiting: "Parent sees the connection waiting on relationship approval.",
        trusted: "Parent sees Teen listed as a trusted friend through the family relationship.",
        blocked: "Parent sees trusted status suspended while the family link is missing.",
        detail: "The parent-child relationship is the authority for this auto-upgrade.",
      },
      approver: {
        title: "Family authority",
        idle: "The approver view is waiting for the parent-child relationship event.",
        pending: "The family relationship is being validated.",
        waiting: "The family relationship is pending before trusted status can apply.",
        trusted: "The family link is recognized and trusted status is active.",
        blocked: "The family link is missing, so trusted status is suspended.",
        notRequired: "No VPC task required: the recognized parent-child relationship is already the approval authority.",
        detail: "Removal and restoration events should be visible from this pane.",
      },
      recipient: {
        title: "Teen's trusted list",
        idle: "Teen has not been linked to Parent in this run yet.",
        pending: "Teen sees the trusted connection being prepared.",
        waiting: "Teen sees the relationship waiting for approval.",
        trusted: "Teen sees Parent as a trusted friend.",
        blocked: "Teen sees trusted status paused until the family link returns.",
        detail: "This view changes when parent-child relationship events arrive.",
      },
    },
    actions: [
      { kind: "start", label: "Form relationship", description: "Auto-add trusted connection." },
      { kind: "removeParentChild", label: "Remove relationship", description: "Async event suspends trusted status." },
      { kind: "restoreParentChild", label: "Restore relationship", description: "Async event restores trusted status." },
    ],
  },
  {
    id: "qr-cross-age",
    title: "QR Cross-Age Rescan",
    navLabel: "QR cross-age",
    group: "Friends API",
    objective: "Existing friends who do not fit same-age double opt-in can re-scan the friend QR code.",
    entryPoint: "Friends API: QR cross-age flow",
    sourceChannel: "QR_CROSS_AGE",
    requester: { id: "riley17", label: "Riley", snapshot: { ...verified, age: 17 } },
    target: { id: "casey19", label: "Casey", snapshot: { ...verified, age: 19 } },
    areFriends: true,
    parentChildRelationship: false,
    autoAccept: true,
    consentTtlSeconds: 120,
    trigger: "QR_CROSS_AGE_RESCAN",
    expectedInitialStatus: "TRUSTED",
    requirements: ["Friends already", "QR re-scan", "Cross-age exception to same-age double opt-in"],
    previews: {
      requester: {
        title: "Riley's QR rescan",
        idle: "Riley can rescan Casey's friend QR code to request trusted status.",
        pending: "Riley sees the QR rescan being evaluated.",
        waiting: "Riley sees the request waiting on required approval.",
        trusted: "Riley sees Casey upgraded to trusted friend status.",
        blocked: "Riley sees that the cross-age QR exception did not apply.",
        detail: "The QR rescan route allows this existing cross-age friendship to auto-upgrade.",
      },
      approver: {
        title: "Approval view",
        idle: "No approval task exists before the QR rescan.",
        pending: "No parent review is queued for this QR rescan exception.",
        waiting: "No parent review is queued for this QR rescan exception.",
        trusted: "No approval was required once the QR cross-age exception matched.",
        blocked: "No approval can override a failed QR or eligibility check.",
        notRequired: "No parent approval required: the QR cross-age rescan is the trusted opt-in signal.",
        detail: "The pane confirms that the exception came from QR_CROSS_AGE.",
      },
      recipient: {
        title: "Casey's QR screen",
        idle: "Casey has not been rescanned in this run yet.",
        pending: "Casey sees the QR rescan request being processed.",
        waiting: "Casey sees the request waiting for approval.",
        trusted: "Casey sees Riley as a trusted friend after the rescan.",
        blocked: "Casey sees that the trusted upgrade is unavailable.",
        detail: "No extra accept click is needed after this QR route.",
      },
    },
    actions: [
      { kind: "start", label: "Re-scan QR", description: "Start trusted flow through QR_CROSS_AGE." },
    ],
  },
  {
    id: "share-link",
    title: "Trusted Friend Share Link",
    navLabel: "Share link",
    group: "Link entry",
    objective: "A clicked trusted friend link can create TF without an existing friendship prerequisite.",
    entryPoint: "Share link click",
    sourceChannel: "SHARE_LINK",
    requester: { id: "sender18", label: "Sender", snapshot: { ...verified, age: 18 } },
    target: { id: "clicker18", label: "Clicker", snapshot: { ...verified, age: 18 } },
    areFriends: false,
    parentChildRelationship: false,
    autoAccept: true,
    consentTtlSeconds: 120,
    trigger: "SHARE_LINK_CLICK",
    expectedInitialStatus: "TRUSTED",
    requirements: ["No existing friendship required", "Click acts as opt-in", "Eligibility still enforced"],
    previews: {
      requester: {
        title: "Sender's share link",
        idle: "Sender can create a trusted friend link for Clicker.",
        pending: "Sender sees the share link click being processed.",
        waiting: "Sender sees the link request paused for approval.",
        trusted: "Sender sees Clicker added as a trusted friend from the link.",
        blocked: "Sender sees that the link cannot create trusted status.",
        detail: "The share-link route skips the existing friendship prerequisite.",
      },
      approver: {
        title: "Approval view",
        idle: "No approval task exists before the link is opened.",
        pending: "No parent review is queued for this eligible share-link flow.",
        waiting: "No parent review is queued for this eligible share-link flow.",
        trusted: "No approval was required after the eligible link click.",
        blocked: "No approval can override a failed eligibility check.",
        notRequired: "No parent approval required: both users are eligible and the link click is the opt-in.",
        detail: "The pane makes the no-friendship-required exception visible.",
      },
      recipient: {
        title: "Clicker's link view",
        idle: "Clicker has not opened Sender's trusted friend link yet.",
        pending: "Clicker sees the link click being confirmed.",
        waiting: "Clicker sees the link waiting for approval.",
        trusted: "Clicker sees Sender as a trusted friend after opening the link.",
        blocked: "Clicker sees that the link is not available.",
        detail: "Opening the link acts as the recipient opt-in.",
      },
    },
    actions: [
      { kind: "start", label: "Open share link", description: "Start trusted connection from a link click." },
    ],
  },
  {
    id: "u13-vpc",
    title: "U13 Verifiable Parental Consent",
    navLabel: "U13 VPC",
    group: "Consent",
    objective: "A U13 user waits on a durable Temporal timer until parental consent is approved or denied.",
    entryPoint: "Friends API + VPC signal",
    sourceChannel: "STANDARD",
    requester: { id: "child12", label: "Child", snapshot: { ...verified, age: 12 } },
    target: { id: "friend14", label: "Friend", snapshot: { ...verified, age: 14 } },
    areFriends: true,
    parentChildRelationship: false,
    autoAccept: false,
    consentTtlSeconds: 120,
    trigger: "U13_VPC_DOUBLE_OPT_IN",
    expectedInitialStatus: "WAITING_FOR_PARENTAL_CONSENT",
    requirements: ["U13 requires VPC globally", "Temporal timer expires the request", "Approval plus acceptance creates TF"],
    previews: {
      requester: {
        title: "Child's request",
        idle: "Child can ask to add Friend as a trusted friend.",
        pending: "Child sees the friend request waiting for Friend to accept.",
        waiting: "Child sees the request waiting for parent approval.",
        trusted: "Child sees Friend added as a trusted friend.",
        blocked: "Child sees that the request was denied or expired.",
        detail: "U13 requests remain durable while the VPC timer is active.",
      },
      approver: {
        title: "Parent approval",
        idle: "Parent has no VPC request to review yet.",
        pending: "Parent can review the trusted friend request before it completes.",
        waiting: "Parent sees a VPC task for Child and can approve or deny.",
        trusted: "Parent sees consent approved for this trusted friend request.",
        blocked: "Parent sees consent denied or the request closed.",
        notRequired: "Approval is required for this scenario because Child is under 13.",
        detail: "Parent approval plus recipient acceptance is required for trusted status.",
      },
      recipient: {
        title: "Friend's inbox",
        idle: "Friend has not received Child's trusted friend prompt yet.",
        pending: "Friend sees Child's request and can accept it.",
        waiting: "Friend sees the request waiting for parent approval.",
        trusted: "Friend sees Child listed as a trusted friend.",
        blocked: "Friend sees the request denied or expired.",
        detail: "Acceptance can happen before or after VPC approval.",
      },
    },
    actions: [
      { kind: "start", label: "Start VPC", description: "Workflow waits for parental consent." },
      { kind: "accept", label: "Accept friend", description: "Signal double opt-in acceptance." },
      { kind: "approveConsent", label: "Approve consent", description: "Signal APPROVED parental consent." },
      { kind: "denyConsent", label: "Deny consent", description: "Signal DENIED parental consent." },
    ],
  },
  {
    id: "eligibility-lost",
    title: "Eligibility Lost Removal",
    navLabel: "Eligibility lost",
    group: "Async processors",
    objective: "A watchlist or verification change removes an active trusted friend connection.",
    entryPoint: "SQS/Kafka eligibility-change consumer",
    sourceChannel: "QR_CODE",
    requester: { id: "safe18", label: "Safe", snapshot: { ...verified, age: 18 } },
    target: { id: "friend18", label: "Friend", snapshot: { ...verified, age: 18 } },
    areFriends: true,
    parentChildRelationship: false,
    autoAccept: true,
    consentTtlSeconds: 120,
    trigger: "ASYNC_ELIGIBILITY_LOSS_SETUP",
    expectedInitialStatus: "TRUSTED",
    requirements: ["Detect eligibility loss", "Suspend trusted status", "Emit TC change event"],
    previews: {
      requester: {
        title: "Safe's trusted list",
        idle: "Safe can seed an active trusted connection with Friend.",
        pending: "Safe sees trusted status being prepared.",
        waiting: "Safe sees the connection paused for approval.",
        trusted: "Safe sees Friend as an active trusted friend.",
        blocked: "Safe sees trusted status suspended after eligibility is lost.",
        detail: "The async eligibility event should remove active trusted access.",
      },
      approver: {
        title: "Approval view",
        idle: "No approval task exists before the pair is seeded.",
        pending: "No parent review is queued for this eligibility-loss scenario.",
        waiting: "No parent review is queued for this eligibility-loss scenario.",
        trusted: "No approval was required while both users were eligible.",
        blocked: "No approval can restore a pair while eligibility is blocked.",
        notRequired: "No parent approval required: this scenario demonstrates safety eligibility enforcement.",
        detail: "The pane stays neutral while async processors own suspension.",
      },
      recipient: {
        title: "Friend's trusted list",
        idle: "Friend has not been connected to Safe in this run yet.",
        pending: "Friend sees trusted status being prepared.",
        waiting: "Friend sees the connection paused for approval.",
        trusted: "Friend sees Safe as an active trusted friend.",
        blocked: "Friend sees trusted status suspended after Safe loses eligibility.",
        detail: "Both sides lose trusted access when the eligibility event lands.",
      },
    },
    actions: [
      { kind: "start", label: "Seed trusted pair", description: "Create an active trusted connection." },
      { kind: "loseEligibility", label: "Lose eligibility", description: "Start eligibility-eval workflow and suspend TF." },
    ],
  },
  {
    id: "eligibility-restored",
    title: "Eligibility Regained Restoration",
    navLabel: "Eligibility restored",
    group: "Async processors",
    objective: "A previously blocked pair is restored when the changed user regains eligibility.",
    entryPoint: "SQS/Kafka eligibility-change consumer",
    sourceChannel: "QR_CODE",
    requester: {
      id: "blocked18",
      label: "Blocked",
      snapshot: { age: 18, country_code: "US", is_age_verified: false, is_on_watchlist: true },
    },
    target: { id: "trusted18", label: "Trusted", snapshot: { ...verified, age: 18 } },
    areFriends: true,
    parentChildRelationship: false,
    autoAccept: true,
    consentTtlSeconds: 120,
    trigger: "ASYNC_ELIGIBILITY_RESTORE_SETUP",
    expectedInitialStatus: "SUSPENDED",
    requirements: ["Add new TF when eligibility is gained", "Restore prior TF after regaining eligibility", "Use deterministic event workflow ID"],
    previews: {
      requester: {
        title: "Blocked's trusted list",
        idle: "Blocked starts ineligible so the seeded pair should begin suspended.",
        pending: "Blocked sees restoration being evaluated.",
        waiting: "Blocked sees the connection paused while approval is checked.",
        trusted: "Blocked sees trusted status restored after eligibility returns.",
        blocked: "Blocked sees trusted status suspended until eligibility is regained.",
        detail: "The restore event should move this pair from suspended back to trusted.",
      },
      approver: {
        title: "Approval view",
        idle: "No approval task exists before the suspended pair is seeded.",
        pending: "No parent review is queued for this restoration scenario.",
        waiting: "No parent review is queued for this restoration scenario.",
        trusted: "No approval was required after eligibility was restored.",
        blocked: "No approval can restore the pair while eligibility remains blocked.",
        notRequired: "No parent approval required: the async eligibility processor owns restoration.",
        detail: "The pane explains that restoration depends on safety eligibility, not parent consent.",
      },
      recipient: {
        title: "Trusted's connection view",
        idle: "Trusted has not been linked to Blocked in this run yet.",
        pending: "Trusted sees restoration being evaluated.",
        waiting: "Trusted sees the connection paused while approval is checked.",
        trusted: "Trusted sees Blocked restored as a trusted friend.",
        blocked: "Trusted sees the connection suspended until eligibility returns.",
        detail: "Both sides should regain trusted access after the restore event.",
      },
    },
    actions: [
      { kind: "start", label: "Seed suspended pair", description: "Start workflow with an ineligible user." },
      { kind: "restoreEligibility", label: "Regain eligibility", description: "Start eligibility-eval workflow and restore TF." },
    ],
  },
  {
    id: "natural-age-up",
    title: "Natural Age-Up Retention",
    navLabel: "Natural age-up",
    group: "Async processors",
    objective: "A U13 connection approved through VPC remains trusted when the child naturally ages up.",
    entryPoint: "Age up/down event consumer",
    sourceChannel: "STANDARD",
    requester: { id: "ageup12", label: "Age-up Child", snapshot: { ...verified, age: 12 } },
    target: { id: "mentor16", label: "Mentor", snapshot: { ...verified, age: 16 } },
    areFriends: true,
    parentChildRelationship: false,
    autoAccept: false,
    consentTtlSeconds: 120,
    trigger: "AGE_UP_AFTER_VPC",
    expectedInitialStatus: "WAITING_FOR_PARENTAL_CONSENT",
    requirements: ["Approved U13 cross-age TF can remain after aging up", "Natural age-up does not revoke TF", "Eligibility event records retention"],
    previews: {
      requester: {
        title: "Age-up Child's request",
        idle: "Age-up Child can request Mentor as a trusted friend with VPC.",
        pending: "Age-up Child sees the request waiting for Mentor to accept.",
        waiting: "Age-up Child sees the request waiting for parent approval.",
        trusted: "Age-up Child sees Mentor remain trusted after aging up.",
        blocked: "Age-up Child sees the request denied, expired, or suspended.",
        detail: "After approval, the natural age-up event should retain trusted status.",
      },
      approver: {
        title: "Parent approval",
        idle: "Parent has no age-up VPC request to review yet.",
        pending: "Parent can review the trusted friend request before it completes.",
        waiting: "Parent sees a VPC task for Age-up Child and can approve or deny.",
        trusted: "Parent sees consent approved and retained after the child ages up.",
        blocked: "Parent sees consent denied or the request closed.",
        notRequired: "Approval is required before the age-up retention behavior can be shown.",
        detail: "VPC approval should survive the natural age-up event.",
      },
      recipient: {
        title: "Mentor's inbox",
        idle: "Mentor has not received the trusted friend prompt yet.",
        pending: "Mentor sees Age-up Child's request and can accept it.",
        waiting: "Mentor sees the request waiting for parent approval.",
        trusted: "Mentor sees Age-up Child remain trusted after aging up.",
        blocked: "Mentor sees the request denied, expired, or suspended.",
        detail: "The recipient view should stay trusted after the age change event.",
      },
    },
    actions: [
      { kind: "start", label: "Start VPC pair", description: "Create a consent-gated cross-age connection." },
      { kind: "accept", label: "Accept", description: "Signal double opt-in acceptance." },
      { kind: "approveConsent", label: "Approve consent", description: "Signal VPC approval." },
      { kind: "ageUp", label: "Age up to 13", description: "Send AGE_CHANGED event and retain TF." },
    ],
  },
];
